### ISSUE TITLE
Connection dropping in the middle of server upload causes window freeze

### ISSUE THREAD

**Issue by fidgetingbits** [fidgetingbits/IDArling#10]
My connection dropped when I was uploading a new idb and I got the attached error and it's not possible to now close the 'Save to server' pop-up dialog that is stuck at 42%

**Comment by fidgetingbits** [comment]
This also seemed to break the ability to upload a new version of the database after the fact. I had to create a new project. I'm not sure why yet.

Also the partially uploaded test version is shown in the database list but is greyed out so that that will need to get fixed.

**Comment by saidelike** [comment]
I'll close this as we forgot to attach he file so will need to recreate an issue with more details the next time it happens
