### ISSUE TITLE
Have a mutex/lock for the delete actions

### ISSUE THREAD

**Issue by saidelike** [fidgetingbits/IDArling#53]
I think we need a lock for the delete database, group and project actions to avoid one person deleting an asset that someone else has currently opened in IDArling.

**Comment by rigmar** [comment]
Hmmm, right. Should prevent deleting only for database? Or for entire project/group? In case  when "Delete group" was clicked for example.
I was thinking just disconnect users and show them some kind of warning. That they could re-save their IDB locally or on server.

**Comment by saidelike** [comment]
Your idea of disconnecting users could work actually, with a message telling them to save the IDB locally. That would be simpler to do.

It should be done for an entire project/group too since another user could have opened a database which is part of this project/group.

**Comment by saidelike** [comment]
For what is worth, this is what we show when trying to rename a project:

![image](https://user-images.githubusercontent.com/387346/83414109-d6e73800-a414-11ea-8c3c-d23c6fc8d064.png)

**Comment by saidelike** [comment]
This is deprecated as we prevent deleting when others are connected, see https://github.com/fidgetingbits/IDArling/pull/58
