### ISSUE TITLE
Server fails to load

### ISSUE THREAD

**Issue by Alberto247** [fidgetingbits/IDArling#67]
While running the server the following error is returned:
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\...\\AppData\\Roaming\\Hex-Rays\\IDA Pro\\plugins\\idarling\\files\\database.db' -> 'C:\\Users\\...\\AppData\\Roaming\\Hex-Rays\\IDA Pro\\plugins\\idarling\\files\\database_1.db'

**Comment by saidelike** [comment]
Closing as was fixed by Vancir. Thanks for reporting
